"""
Seed the DB with initial categories and a starter set of real API services.
Run once: python -m app.seed
sAIge to validate each service against live APIs before adding more.
"""
from app.database import SessionLocal, engine
from app.models import Base, Category, Service

CATEGORIES = [
    {"slug": "tts", "label": "Text to Speech"},
    {"slug": "stt", "label": "Speech to Text"},
    {"slug": "llm", "label": "Large Language Models"},
    {"slug": "image-gen", "label": "Image Generation"},
    {"slug": "embeddings", "label": "Embeddings"},
    {"slug": "search", "label": "Search"},
    {"slug": "code", "label": "Code Generation"},

    # Emerging machine-first categories
    {"slug": "policy-decision", "label": "Policy Decision"},
    {"slug": "prompt-security", "label": "Prompt Security"},
    {"slug": "pii-redaction", "label": "PII Redaction"},
    {"slug": "provenance", "label": "Provenance"},
    {"slug": "vendor-risk", "label": "Vendor Risk"},
    {"slug": "consent", "label": "Consent & Preferences"},
    {"slug": "human-loop", "label": "Human-in-the-Loop"},
    {"slug": "agent-observability", "label": "Agent Observability"},
    {"slug": "change-intel", "label": "Change Intelligence"},
    {"slug": "carbon-intensity", "label": "Carbon & Energy"},

    {"slug": "mcp", "label": "MCP Servers"},
    {"slug": "dispute-resolution", "label": "Dispute Resolution"},
    {"slug": "ethical-reasoning", "label": "Ethical Reasoning"},
    {"slug": "registry", "label": "Agent Registry"},
    {"slug": "other", "label": "Other"},
]

SERVICES = [
    {
        "slug": "elevenlabs-tts",
        "name": "ElevenLabs TTS",
        "canonical_provider": "ElevenLabs",
        "category_slug": "tts",
        "description": "High-quality AI voice synthesis with voice cloning support.",
        "docs_url": "https://elevenlabs.io/docs/api-reference",
        "base_url": "https://api.elevenlabs.io",
        "auth_type": "api_key",
        "pricing_model": "usage_based",
        "pricing_notes": "Free tier: 10k chars/mo. Paid from $5/mo.",
        "status": "approved",
    },
    {
        "slug": "openai-tts",
        "name": "OpenAI TTS",
        "canonical_provider": "OpenAI",
        "category_slug": "tts",
        "description": "OpenAI text-to-speech API with multiple voice options.",
        "docs_url": "https://platform.openai.com/docs/guides/text-to-speech",
        "base_url": "https://api.openai.com/v1/audio/speech",
        "auth_type": "api_key",
        "pricing_model": "per_request",
        "pricing_notes": "$15/1M chars for tts-1, $30/1M chars for tts-1-hd.",
        "status": "approved",
    },
    {
        "slug": "openai-whisper",
        "name": "OpenAI Whisper STT",
        "canonical_provider": "OpenAI",
        "category_slug": "stt",
        "description": "Speech-to-text transcription via OpenAI Whisper model.",
        "docs_url": "https://platform.openai.com/docs/guides/speech-to-text",
        "base_url": "https://api.openai.com/v1/audio/transcriptions",
        "auth_type": "api_key",
        "pricing_model": "per_request",
        "pricing_notes": "$0.006/minute.",
        "status": "approved",
    },
    {
        "slug": "anthropic-claude",
        "name": "Anthropic Claude API",
        "canonical_provider": "Anthropic",
        "category_slug": "llm",
        "description": "Claude family of LLMs — Haiku, Sonnet, Opus. Strong reasoning and tool use.",
        "docs_url": "https://docs.anthropic.com",
        "base_url": "https://api.anthropic.com",
        "auth_type": "api_key",
        "pricing_model": "per_request",
        "pricing_notes": "From $0.25/M tokens (Haiku) to $15/M tokens (Opus).",
        "status": "approved",
    },
    {
        "slug": "openai-gpt4",
        "name": "OpenAI GPT-4o",
        "canonical_provider": "OpenAI",
        "category_slug": "llm",
        "description": "OpenAI flagship multimodal LLM with vision and tool use.",
        "docs_url": "https://platform.openai.com/docs",
        "base_url": "https://api.openai.com/v1",
        "auth_type": "api_key",
        "pricing_model": "per_request",
        "pricing_notes": "$2.50/M input tokens, $10/M output tokens.",
        "status": "approved",
    },
    {
        "slug": "deepseek-chat",
        "name": "DeepSeek Chat API",
        "canonical_provider": "DeepSeek",
        "category_slug": "llm",
        "description": "Cost-efficient LLM with strong coding and reasoning performance.",
        "docs_url": "https://platform.deepseek.com/api-docs",
        "base_url": "https://api.deepseek.com",
        "auth_type": "api_key",
        "pricing_model": "per_request",
        "pricing_notes": "From $0.07/M tokens — very low cost.",
        "status": "approved",
    },
    {
        "slug": "openai-embeddings",
        "name": "OpenAI Embeddings",
        "canonical_provider": "OpenAI",
        "category_slug": "embeddings",
        "description": "Text embedding models for semantic search and retrieval.",
        "docs_url": "https://platform.openai.com/docs/guides/embeddings",
        "base_url": "https://api.openai.com/v1/embeddings",
        "auth_type": "api_key",
        "pricing_model": "per_request",
        "pricing_notes": "$0.02/M tokens (text-embedding-3-small).",
        "status": "approved",
    },
    {
        "slug": "stability-image-gen",
        "name": "Stability AI Image Generation",
        "canonical_provider": "Stability AI",
        "category_slug": "image-gen",
        "description": "Stable Diffusion image generation via API.",
        "docs_url": "https://platform.stability.ai/docs/api-reference",
        "base_url": "https://api.stability.ai",
        "auth_type": "api_key",
        "pricing_model": "per_request",
        "pricing_notes": "From $0.01 per image.",
        "status": "approved",
    },
    {
        "slug": "serper-search",
        "name": "Serper Google Search API",
        "canonical_provider": "Serper",
        "category_slug": "search",
        "description": "Real-time Google search results via REST API. Popular with AI agents.",
        "docs_url": "https://serper.dev/docs",
        "base_url": "https://google.serper.dev",
        "auth_type": "api_key",
        "pricing_model": "per_request",
        "pricing_notes": "Free tier: 2500 queries. Paid from $50/50k queries.",
        "status": "approved",
    },
    {
        "slug": "github-copilot-api",
        "name": "GitHub Copilot API",
        "canonical_provider": "GitHub",
        "category_slug": "code",
        "description": "AI code completion and generation via GitHub Copilot.",
        "docs_url": "https://docs.github.com/en/copilot",
        "base_url": "https://api.githubcopilot.com",
        "auth_type": "oauth",
        "pricing_model": "subscription",
        "pricing_notes": "$10/mo individual, $19/mo business.",
        "status": "approved",
    },
    # --- TTS ---
    {
        "slug": "playht-tts",
        "name": "PlayHT TTS",
        "canonical_provider": "PlayHT",
        "category_slug": "tts",
        "description": "Text-to-speech with 900+ voices and real-time voice cloning.",
        "docs_url": "https://docs.play.ht/reference/api-getting-started",
        "base_url": "https://api.play.ht",
        "auth_type": "api_key",
        "pricing_model": "usage_based",
        "pricing_notes": "Free tier: 12.5k chars/mo. Paid from $31.20/mo.",
        "status": "approved",
    },
    {
        "slug": "lmnt-tts",
        "name": "LMNT TTS",
        "canonical_provider": "LMNT",
        "category_slug": "tts",
        "description": "Ultra-low latency streaming TTS. Sub-second response for real-time apps.",
        "docs_url": "https://docs.lmnt.com",
        "base_url": "https://api.lmnt.com",
        "auth_type": "api_key",
        "pricing_model": "usage_based",
        "pricing_notes": "Free tier: 500 chars/mo. Paid from $0.01/1k chars.",
        "status": "approved",
    },
    {
        "slug": "cartesia-tts",
        "name": "Cartesia TTS",
        "canonical_provider": "Cartesia",
        "category_slug": "tts",
        "description": "Real-time streaming TTS with voice cloning. Designed for low-latency agent pipelines.",
        "docs_url": "https://docs.cartesia.ai",
        "base_url": "https://api.cartesia.ai",
        "auth_type": "api_key",
        "pricing_model": "usage_based",
        "pricing_notes": "Free tier: 1M chars/mo. Paid from $0.0005/char.",
        "status": "approved",
    },
    # --- STT ---
    {
        "slug": "assemblyai-stt",
        "name": "AssemblyAI STT",
        "canonical_provider": "AssemblyAI",
        "category_slug": "stt",
        "description": "Best-in-class STT with speaker diarization, sentiment analysis, and summarization.",
        "docs_url": "https://www.assemblyai.com/docs",
        "base_url": "https://api.assemblyai.com",
        "auth_type": "api_key",
        "pricing_model": "per_request",
        "pricing_notes": "$0.37/hr audio. Free tier available.",
        "status": "approved",
    },
    {
        "slug": "deepgram-stt",
        "name": "Deepgram STT",
        "canonical_provider": "Deepgram",
        "category_slug": "stt",
        "description": "Fastest real-time STT API. Low latency streaming, 30+ languages.",
        "docs_url": "https://developers.deepgram.com/docs",
        "base_url": "https://api.deepgram.com",
        "auth_type": "api_key",
        "pricing_model": "per_request",
        "pricing_notes": "$0.0043/min (Nova-2). Free tier: $200 credit.",
        "status": "approved",
    },
    {
        "slug": "gladia-stt",
        "name": "Gladia STT",
        "canonical_provider": "Gladia",
        "category_slug": "stt",
        "description": "Multilingual STT with real-time transcription and translation. 100+ languages.",
        "docs_url": "https://docs.gladia.io",
        "base_url": "https://api.gladia.io",
        "auth_type": "api_key",
        "pricing_model": "per_request",
        "pricing_notes": "Free tier: 10hrs/mo. Paid from $0.0146/min.",
        "status": "approved",
    },
    # --- LLM ---
    {
        "slug": "groq-llm",
        "name": "Groq LLM API",
        "canonical_provider": "Groq",
        "category_slug": "llm",
        "description": "Ultra-fast LLM inference on custom LPU hardware. Llama, Mixtral, Gemma models.",
        "docs_url": "https://console.groq.com/docs",
        "base_url": "https://api.groq.com",
        "auth_type": "api_key",
        "pricing_model": "per_request",
        "pricing_notes": "From $0.05/M tokens (Llama 3 8B). Free tier available.",
        "status": "approved",
    },
    {
        "slug": "together-ai-llm",
        "name": "Together AI",
        "canonical_provider": "Together AI",
        "category_slug": "llm",
        "description": "Open-source LLM inference. 50+ models including Llama, Mistral, Qwen.",
        "docs_url": "https://docs.together.ai",
        "base_url": "https://api.together.xyz",
        "auth_type": "api_key",
        "pricing_model": "per_request",
        "pricing_notes": "From $0.01/M tokens. Free tier: $1 credit.",
        "status": "approved",
    },
    # --- Embeddings ---
    {
        "slug": "cohere-embeddings",
        "name": "Cohere Embeddings",
        "canonical_provider": "Cohere",
        "category_slug": "embeddings",
        "description": "Best-in-class retrieval embeddings. Embed-v3 optimised for semantic search and RAG.",
        "docs_url": "https://docs.cohere.com/docs/embeddings",
        "base_url": "https://api.cohere.com",
        "auth_type": "api_key",
        "pricing_model": "per_request",
        "pricing_notes": "$0.10/M tokens. Free tier: 1k calls/mo.",
        "status": "approved",
    },
    {
        "slug": "voyage-ai-embeddings",
        "name": "Voyage AI Embeddings",
        "canonical_provider": "Voyage AI",
        "category_slug": "embeddings",
        "description": "Specialised embeddings for RAG. State-of-the-art retrieval performance.",
        "docs_url": "https://docs.voyageai.com",
        "base_url": "https://api.voyageai.com",
        "auth_type": "api_key",
        "pricing_model": "per_request",
        "pricing_notes": "$0.12/M tokens. Free tier: 50M tokens/mo.",
        "status": "approved",
    },
    {
        "slug": "jina-ai-embeddings",
        "name": "Jina AI Embeddings",
        "canonical_provider": "Jina AI",
        "category_slug": "embeddings",
        "description": "Multilingual embeddings with free tier. 8k context, 89 languages.",
        "docs_url": "https://jina.ai/embeddings",
        "base_url": "https://api.jina.ai",
        "auth_type": "api_key",
        "pricing_model": "usage_based",
        "pricing_notes": "Free tier: 1M tokens. Paid from $0.02/M tokens.",
        "status": "approved",
    },
    # --- Image Generation ---
    {
        "slug": "replicate-image-gen",
        "name": "Replicate",
        "canonical_provider": "Replicate",
        "category_slug": "image-gen",
        "description": "Run any open-source image model via API. SDXL, Flux, ControlNet, and more.",
        "docs_url": "https://replicate.com/docs",
        "base_url": "https://api.replicate.com",
        "auth_type": "api_key",
        "pricing_model": "per_request",
        "pricing_notes": "Pay per compute second. ~$0.003–0.05/image depending on model.",
        "status": "approved",
    },
    {
        "slug": "fal-ai-image-gen",
        "name": "fal.ai Image Generation",
        "canonical_provider": "fal.ai",
        "category_slug": "image-gen",
        "description": "Fast, cheap image generation. Flux, SDXL, ControlNet. Sub-second inference.",
        "docs_url": "https://fal.ai/docs",
        "base_url": "https://fal.run",
        "auth_type": "api_key",
        "pricing_model": "per_request",
        "pricing_notes": "From $0.002/image. No subscription needed.",
        "status": "approved",
    },
    {
        "slug": "ideogram-image-gen",
        "name": "Ideogram API",
        "canonical_provider": "Ideogram",
        "category_slug": "image-gen",
        "description": "Image generation with excellent text rendering. Strong for logos and typography.",
        "docs_url": "https://developer.ideogram.ai/api-reference",
        "base_url": "https://api.ideogram.ai",
        "auth_type": "api_key",
        "pricing_model": "per_request",
        "pricing_notes": "From $0.02/image.",
        "status": "approved",
    },
    # --- TTS (apiale gaps 2026-03-12) ---
    {
        "slug": "xai-tts",
        "name": "xAI Aurora TTS",
        "canonical_provider": "xAI",
        "category_slug": "tts",
        "description": "xAI's Aurora voice model — expressive, natural TTS via OpenAI-compatible API. Part of the Grok platform.",
        "docs_url": "https://docs.x.ai/docs/guides/audio",
        "base_url": "https://api.x.ai/v1",
        "auth_type": "api_key",
        "pricing_model": "per_request",
        "pricing_notes": "~$15/1M chars. Same API format as OpenAI TTS.",
        "status": "approved",
    },
    {
        "slug": "edge-tts",
        "name": "Microsoft Edge TTS",
        "canonical_provider": "Microsoft",
        "category_slug": "tts",
        "description": "Free TTS via Microsoft Edge/Bing speech service. 400+ voices, 140+ languages. No API key required. Accessible via edge-tts Python library.",
        "docs_url": "https://github.com/rany2/edge-tts",
        "base_url": "https://speech.platform.bing.com",
        "auth_type": "none",
        "pricing_model": "free",
        "pricing_notes": "Free. Unofficial/undocumented API — no SLA or rate limit guarantees.",
        "status": "approved",
    },
    {
        "slug": "murf-ai-tts",
        "name": "Murf AI TTS",
        "canonical_provider": "Murf AI",
        "category_slug": "tts",
        "description": "TTS with strong accent and dialect control. 120+ voices across US, UK, Australian, Indian English and more. Good for localisation pipelines.",
        "docs_url": "https://murf.ai/api/docs",
        "base_url": "https://api.murf.ai",
        "auth_type": "api_key",
        "pricing_model": "usage_based",
        "pricing_notes": "Free tier: 10 mins/mo. Paid from $29/mo.",
        "status": "approved",
    },
    # --- Search ---
    {
        "slug": "brave-search-api",
        "name": "Brave Search API",
        "canonical_provider": "Brave",
        "category_slug": "search",
        "description": "Independent web search API. No Google dependency. AI summaries included.",
        "docs_url": "https://api.search.brave.com/app/documentation",
        "base_url": "https://api.search.brave.com",
        "auth_type": "api_key",
        "pricing_model": "per_request",
        "pricing_notes": "Free tier: 2k queries/mo. Paid from $3/1k queries.",
        "status": "approved",
    },
    {
        "slug": "tavily-search",
        "name": "Tavily Search API",
        "canonical_provider": "Tavily",
        "category_slug": "search",
        "description": "AI-optimised search API built for agents. Returns structured, clean results.",
        "docs_url": "https://docs.tavily.com",
        "base_url": "https://api.tavily.com",
        "auth_type": "api_key",
        "pricing_model": "per_request",
        "pricing_notes": "Free tier: 1k queries/mo. Paid from $35/1k queries.",
        "status": "approved",
    },
    # --- From apiale CRM gap reports 2026-03-18 ---
    {
        "slug": "resemble-ai-tts",
        "name": "Resemble AI TTS",
        "canonical_provider": "Resemble AI",
        "category_slug": "tts",
        "description": "Custom voice cloning and accent-specific TTS. Supports regional dialects and voice customization for localisation pipelines. Real-time streaming available.",
        "docs_url": "https://docs.resemble.ai",
        "base_url": "https://app.resemble.ai/api/v2",
        "auth_type": "api_key",
        "pricing_model": "usage_based",
        "pricing_notes": "From $0.006/sec audio. Free tier: 10k chars/mo.",
        "status": "approved",
    },
    {
        "slug": "scale-ai",
        "name": "Scale AI Tasker API",
        "canonical_provider": "Scale AI",
        "category_slug": "human-loop",
        "description": "Human labeling and review API. Agents submit tasks for human verification, annotation, or decision. Supports RLHF, data labeling, content moderation.",
        "docs_url": "https://docs.scale.com",
        "base_url": "https://api.scale.com/v1",
        "auth_type": "api_key",
        "pricing_model": "per_request",
        "pricing_notes": "Custom pricing. Free tier for small volumes.",
        "status": "approved",
    },
    {
        "slug": "unstructured-io",
        "name": "Unstructured.io",
        "canonical_provider": "Unstructured",
        "category_slug": "other",
        "description": "Document parsing API for complex PDFs, Word docs, HTML. Extracts clean structured text from messy layouts. Essential for RAG pipelines.",
        "docs_url": "https://unstructured-io.github.io/unstructured",
        "base_url": "https://api.unstructured.io",
        "auth_type": "api_key",
        "pricing_model": "usage_based",
        "pricing_notes": "Free tier: 1000 pages/mo. Paid from $10/mo.",
        "status": "approved",
    },
    {
        "slug": "infisical",
        "name": "Infisical Secrets API",
        "canonical_provider": "Infisical",
        "category_slug": "other",
        "description": "Open-source secrets management API. Agents fetch env vars and secrets at runtime. Supports dynamic secrets, secret rotation, audit logs.",
        "docs_url": "https://infisical.com/docs/api-reference/overview/introduction",
        "base_url": "https://app.infisical.com/api",
        "auth_type": "api_key",
        "pricing_model": "free",
        "pricing_notes": "Open-source self-hostable. Cloud free tier available.",
        "status": "approved",
    },
    {
        "slug": "aws-textract",
        "name": "AWS Textract",
        "canonical_provider": "Amazon Web Services",
        "category_slug": "other",
        "description": "ML-powered document text extraction. Handles complex PDF layouts, tables, forms. Strong for invoices, contracts, and scanned documents.",
        "docs_url": "https://docs.aws.amazon.com/textract",
        "base_url": "https://textract.amazonaws.com",
        "auth_type": "api_key",
        "pricing_model": "per_request",
        "pricing_notes": "$1.50/1k pages (text). Free tier: 100 pages/mo.",
        "status": "approved",
    },
    {
        "slug": "cal-com",
        "name": "Cal.com Scheduling API",
        "canonical_provider": "Cal.com",
        "category_slug": "human-loop",
        "description": "Open-source scheduling API. Agents book meetings, check availability, manage calendars. Timezone-aware, supports round-robin and team scheduling.",
        "docs_url": "https://cal.com/docs/api-reference",
        "base_url": "https://api.cal.com/v1",
        "auth_type": "api_key",
        "pricing_model": "free",
        "pricing_notes": "Open-source self-hostable. Cloud free tier available.",
        "status": "approved",
    },
    {
        "slug": "naim-registry",
        "name": "nAIm API Registry",
        "canonical_provider": "naim.janis7ewski.org",
        "category_slug": "registry",
        "description": "Machine-first registry of AI agent API services. Discover, compare and rate APIs by category, pricing, auth type, and peer ratings from other agents. Read endpoints unauthenticated.",
        "docs_url": "https://api.naim.janis7ewski.org/docs",
        "base_url": "https://api.naim.janis7ewski.org",
        "auth_type": "api_key",
        "pricing_model": "free",
        "pricing_notes": "Fully free. Read endpoints require no auth. Write endpoints require X-API-Key.",
        "status": "approved",
        "verified": True,
    },
]


def seed():
    Base.metadata.create_all(bind=engine)
    db = SessionLocal()
    try:
        for cat in CATEGORIES:
            if not db.query(Category).filter(Category.slug == cat["slug"]).first():
                db.add(Category(**cat))

        db.commit()

        for svc in SERVICES:
            if not db.query(Service).filter(Service.slug == svc["slug"]).first():
                db.add(Service(**svc))

        db.commit()
        print(f"Seeded {len(CATEGORIES)} categories and {len(SERVICES)} services.")
    finally:
        db.close()


if __name__ == "__main__":
    seed()
